; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = ../boards
default_envs = seeed_xiao

[env]
framework = arduino
lib_deps = 
	tcMenu
	TaskManagerIO
	IoAbstraction
	tcUnicodeHelper
monitor_speed = 115200
upload_speed = 460800
custom_build_flags_deps = 

[env:seeed_xiao]
platform = atmelsam
board = seeed_xiao
;platform = https://github.com/Seeed-Studio/platform-seeedboards.git # produces 'bossac' is not recognized Error 1 ?
;board = seeed-xiao-samd # produces 'bossac' is not recognized Error 1 ?
; google says that samd21 does not use this in the same way as an esp23 - board_build.partitions = min_spiffs.csv
build_flags = 
	${env.build_flags}
	-I ../boards
	-D INIDEF_SEEED_XIAO_SAMD21
lib_deps = 
	${env.lib_deps}
	u8g2@2.35.30
;	fortyseveneffects/MIDI Library@^5.0.2
;	lathoub/USB-MIDI@^1.1.3
;	lathoub/USB-MIDI@^1.1.2
;	arduino-libraries/MIDIUSB@^1.0.5

[env:esp32dev_cyd]
platform = espressif32
board = esp32dev
monitor_filters = esp32_exception_decoder
board_build.partitions = min_spiffs.csv
build_flags = 
	${env.build_flags}
	-I ../boards
	-D INIDEF_ESP32DEV_CYD
	-DUSER_SETUP_LOADED
	-DUSE_HSPI_PORT
	-DTFT_MISO=12
	-DTFT_MOSI=13
	-DTFT_SCLK=14
	-DTFT_CS=15
	-DTFT_DC=2
	-DTFT_RST=-1
	-DTFT_BL=21
	-DTFT_BACKLIGHT_ON=HIGH
	-DSPI_FREQUENCY=55000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000
	-DLOAD_GLCD
	-DLOAD_FONT2
	-DLOAD_FONT4
	-DLOAD_FONT6
	-DLOAD_FONT7
	-DLOAD_FONT8
	-DLOAD_GFXFF
	-DILI9341_2_DRIVER
lib_deps = 
	${env.lib_deps}
	bodmer/TFT_eSPI
	fortyseveneffects/MIDI Library@^5.0.2
	lathoub/USB-MIDI@^1.1.3
	arduino-libraries/MIDIUSB@^1.0.5

[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
build_flags = 
	${env.custom_build_flags_deps}
	-I ../boards
	-D INIDEF_LILYGO_T_DISPLAY_S3
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
lib_deps = 
	${env.lib_deps}
	TFT_eSPI
	movingAvg
	arduino-timer
	elapsedMillis
	WiFi
	ESP32Servo
	erropix/ESP32 AnalogWrite@^0.2
	VirtSerial
	CommsHelper
	SerialCommand
	fortyseveneffects/MIDI Library@^5.0.2
	lathoub/USB-MIDI@^1.1.3
	arduino-libraries/MIDIUSB@^1.0.5

[env:lilygo-t7-s3]
platform = espressif32
board = lilygo-t7-s3
build_flags = 
	${env.custom_build_flags_deps}
	-I ../boards
	-D INIDEF_LILYGO_T7_S3
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
lib_deps = 
	${env.lib_deps}
	LiquidCrystalIO
	Adafruit GFX Library
	Adafruit ILI9341
	movingAvg
	arduino-timer
	elapsedMillis
	WiFi
	ESP32Servo
	erropix/ESP32 AnalogWrite@^0.2
	fortyseveneffects/MIDI Library@^5.0.2
	lathoub/USB-MIDI@^1.1.3
	arduino-libraries/MIDIUSB@^1.0.5

[env:lilygo-t-embed-s3]
platform = espressif32
board = lilygo-t-embed
monitor_speed = 115200
build_flags = 
	${env.custom_build_flags_deps}
	-I ../boards
	-D INIDEF_LILYGO_T_EMBED_S3
	-D INIDEF_ARDUINOOTA
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D SOC_SDMMC_HOST_SUPPORTED
lib_deps = 
	${env.lib_deps}
	TFT_eSPI@2.5.30
	FS
	SPIFFS
	SPI
	Serial
	WiFi
	ESP32Servo
	arduino-timer
	movingAvg
	erropix/ESP32 AnalogWrite@^0.2
	fortyseveneffects/MIDI Library@^5.0.2
	lathoub/USB-MIDI@^1.1.3
	arduino-libraries/MIDIUSB@^1.0.5

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_flags = 
	-D INIDEF_MEGA2560
	-I ../boards
lib_deps = 
	${env.lib_deps}
	LiquidCrystalIO
	Adafruit GFX Library
	Adafruit BusIO
	Adafruit ILI9341
	Servo
	arduino-timer
	movingAvg
	fortyseveneffects/MIDI Library@^5.0.2
	lathoub/USB-MIDI@^1.1.3
	arduino-libraries/MIDIUSB@^1.0.5
