/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

// Generated for Arduino 32bit ARM by TcMenu 4.4.0 on 2025-11-11T11:37:34.957302300Z.

#include <tcMenu.h>
#include "xiao-samd21-tcmenu-i2c-pcf8575-rotaryencoder-test_menu.h"
#include "ThemeMonoInverseBuilder.h"

// Global variable declarations
const  ConnectorLocalInfo applicationInfo = { "samd21 251111 1953*", "f5a35aa5-3ae6-46fe-900a-7d6749bd049c" };
IoAbstractionRef ioexp_myI2CExpansion = ioFrom23017(0x20, ACTIVE_LOW_OPEN, 2);
U8G2_SSD1306_128X64_NONAME_F_HW_I2C gfx(U8G2_R0, U8X8_PIN_NONE, 5, 4);
U8g2Drawable gfxDrawable(&gfx);
GraphicsDeviceRenderer renderer(30, applicationInfo.name, &gfxDrawable);

// Global Menu Item declarations
const AnalogMenuInfo minfoTcmUpSeconds = { "UpSeconds", 3, 0xffff, 255, onChangeTcmUpSeconds, 0, 1, "" };
AnalogMenuItem menuTcmUpSeconds(&minfoTcmUpSeconds, 0, nullptr, INFO_LOCATION_PGM);
const AnalogMenuInfo minfoNewAnalogItem = { "New AnalogItem", 2, 0xffff, 255, NO_CALLBACK, 0, 1, "" };
AnalogMenuItem menuNewAnalogItem(&minfoNewAnalogItem, 0, &menuTcmUpSeconds, INFO_LOCATION_PGM);
const BooleanMenuInfo minfoTcmMyLED = { "MyLED", 1, 0xffff, 1, onChangeTcmMyLED, NAMING_TRUE_FALSE };
BooleanMenuItem menuTcmMyLED(&minfoTcmMyLED, false, &menuNewAnalogItem, INFO_LOCATION_PGM);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    setSizeBasedEEPROMStorageEnabled(false);
    // Code generated by plugins and new operators.
    gfx.begin();
    renderer.setUpdatesPerSecond(10);
    switches.init(ioexp_myI2CExpansion, SWITCHES_NO_POLLING, true);
    menuMgr.initForEncoder(&renderer, &menuTcmMyLED, 6, 5, 7);
    installMonoInverseTitleTheme(renderer, MenuFontDef(nullptr, 1), MenuFontDef(nullptr, 1), true, BaseGraphicalRenderer::TITLE_FIRST_ROW, false);
}

